global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: web_gateway

certificatesResolvers:
  letsencrypt:
    acme:
      email: "patcocloud@gmail.com"
      storage: "/acme.json"
      httpChallenge:
        entryPoint: web